export const chatMessages = [
  {
    _id: "msg_001",
    chatId: "chat_88",
    text: "Hey Ali! Did you finish the luqya UI?",
    sender: {
      _id: "user_2",
      FullName: "Sarah J.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    file: { url: null, fileType: "none" },
    status: "seen",
    createdAt: "2026-02-09T10:00:00.000Z",
  },
  {
    _id: "msg_002",
    chatId: "chat_88",
    text: "Almost! Just fixing the keyboard avoiding view issue now 🛠️",
    sender: {
      _id: "user_1",
      FullName: "Ali Edris",
      avatar: "https://musdar.com/avatar.png",
    },
    file: { url: null, fileType: "none" },
    status: "seen",
    createdAt: "2026-02-09T10:01:30.000Z",
  },
  {
    _id: "msg_003",
    chatId: "chat_88",
    text: "",
    sender: {
      _id: "user_2",
      FullName: "Sarah J.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    file: {
      url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97",
      fileType: "image",
    },
    status: "delivered",
    createdAt: "2026-02-09T10:05:00.000Z",
  },
  {
    _id: "msg_004",
    chatId: "chat_88",
    text: "Check out this screenshot for inspiration.",
    sender: {
      _id: "user_2",
      FullName: "Sarah J.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    file: { url: null, fileType: "none" },
    status: "delivered",
    createdAt: "2026-02-09T10:05:10.000Z",
  },
  {
    _id: "msg_005",
    chatId: "chat_88",
    text: "Looks great! I'll implement that color scheme.",
    sender: {
      _id: "user_1",
      FullName: "Ali Edris",
      avatar: "https://musdar.com/avatar.png",
    },
    file: { url: null, fileType: "none" },
    status: "sent",
    createdAt: "2026-02-09T10:08:00.000Z",
  },
  {
    _id: "msg_006",
    chatId: "chat_88",
    text: "By the way, did you check the new Socket.io logic?",
    sender: {
      _id: "user_2",
      FullName: "Sarah J.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    file: { url: null, fileType: "none" },
    status: "seen",
    createdAt: "2026-02-09T10:10:00.000Z",
  },
  {
    _id: "msg_007",
    chatId: "chat_88",
    text: "Yes, the online status is working perfectly now.",
    sender: {
      _id: "user_1",
      FullName: "Ali Edris",
      avatar: "https://musdar.com/avatar.png",
    },
    file: { url: null, fileType: "none" },
    status: "seen",
    createdAt: "2026-02-09T10:12:00.000Z",
  },
  {
    _id: "msg_008",
    chatId: "chat_88",
    text: "I am testing the unfriend button logic as well.",
    sender: {
      _id: "user_1",
      FullName: "Ali Edris",
      avatar: "https://musdar.com/avatar.png",
    },
    file: { url: null, fileType: "none" },
    status: "seen",
    createdAt: "2026-02-09T10:15:00.000Z",
  },
  {
    _id: "msg_009",
    chatId: "chat_88",
    text: "Perfect! Luqya is coming together nicely.",
    sender: {
      _id: "user_2",
      FullName: "Sarah J.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    },
    file: { url: null, fileType: "none" },
    status: "delivered",
    createdAt: "2026-02-09T10:18:00.000Z",
  },
  {
    _id: "msg_010",
    chatId: "chat_88",
    text: "I'll send you the APK for testing later today.",
    sender: {
      _id: "user_1",
      FullName: "Ali Edris",
      avatar: "https://musdar.com/avatar.png",
    },
    file: { url: null, fileType: "none" },
    status: "sent",
    createdAt: "2026-02-09T10:20:00.000Z",
  },
];
